<?php

class phone_number {
    public $region;
    public $number_id;

    // Constructor to initialize region and number_id
    public function __construct($region, $number_id) {
        $this->region = $region;
        $this->number_id = $number_id;
    }

    // Function to get the formatted phone number with region
    public function getFormattedNumber() {
        return $this->region . ' (' . $this->number_id . ')';
    }
}

// Array of phone numbers with region and number_id
$phone_numbers = array(
    new phone_number('Afghanistan', '+93'),
    new phone_number('Albania', '+355'),
    new phone_number('Algeria', '+213'),
    new phone_number('American Samoa', '+1684'),
    new phone_number('Andorra', '+376'),
    new phone_number('Angola', '+244'),
    new phone_number('Anguilla', '+1264'),
    new phone_number('Antigua & Barbuda', '+1268'),
    new phone_number('Argentina', '+54'),
    new phone_number('Armenia', '+374'),
    new phone_number('Aruba', '+297'),
    new phone_number('Australia', '+61'),
    new phone_number('Austria', '+43'),
    new phone_number('Azerbaijan', '+994'),
    new phone_number('Bahamas', '+1242'),
    new phone_number('Bahrain', '+973'),
    new phone_number('Bangladesh', '+880'),
    new phone_number('Barbados', '+1246'),
    new phone_number('Belarus', '+375'),
    new phone_number('Belgium', '+32'),
    new phone_number('Belize', '+501'),
    new phone_number('Benin', '+229'),
    new phone_number('Bermuda', '+1441'),
    new phone_number('Bhutan', '+975'),
    new phone_number('Bolivia', '+591'),
    new phone_number('Bosnia & Herzegovina', '+387'),
    new phone_number('Botswana', '+267'),
    new phone_number('Brazil', '+55'),
    new phone_number('British Indian Ocean Territory', '+246'),
    new phone_number('British Virgin Islands', '+1284'),
    new phone_number('Brunei', '+673'),
    new phone_number('Bulgaria', '+359'),
    new phone_number('Burkina Faso', '+226'),
    new phone_number('Burma (Myanmar)', '+95'),
    new phone_number('Burundi', '+257'),
    new phone_number('Cambodia', '+855'),
    new phone_number('Cameroon', '+237'),
    new phone_number('Canada', '+1'),
    new phone_number('Cape Verde', '+238'),
    new phone_number('Cayman Islands', '+1345'),
    new phone_number('Central African Republic', '+236'),
    new phone_number('Chad', '+235'),
    new phone_number('Chile', '+56'),
    new phone_number('China', '+86'),
    new phone_number('Christmas Island', '+6189'),
    new phone_number('Colombia', '+57'),
    new phone_number('Comoros', '+269'),
    new phone_number('Congo - Brazzaville', '+242'),
    new phone_number('Congo - Kinshasa', '+243'),
    new phone_number('Cook Islands', '+682'),
    new phone_number('Costa Rica', '+506'),
    new phone_number('Croatia', '+385'),
    new phone_number('Cuba', '+53'),
    new phone_number('Cyprus', '+357'),
    new phone_number('Czechia', '+420'),
    new phone_number('Denmark', '+45'),
    new phone_number('Djibouti', '+253'),
    new phone_number('Dominica', '+1767'),
    new phone_number('Dominican Republic', '+1849'),
    new phone_number('Dominican Republic', '+1829'),
    new phone_number('Dominican Republic', '+1809'),
    new phone_number('Timor-Leste', '+670'),
    new phone_number('Ecuador', '+593'),
    new phone_number('Egypt', '+20'),
    new phone_number('El Salvador', '+503'),
    new phone_number('Equatorial Guinea', '+240'),
    new phone_number('Eritrea', '+291'),
    new phone_number('Estonia', '+372'),
    new phone_number('Ethiopia', '+251'),
    new phone_number('Faroe Islands', '+298'),
    new phone_number('Fiji', '+679'),
    new phone_number('Finland', '+358'),
    new phone_number('France', '+33'),
    new phone_number('French Guiana', '+594'),
    new phone_number('French Polynesia', '+689'),
    new phone_number('Gabon', '+241'),
    new phone_number('Gambia', '+220'),
    new phone_number('Georgia', '+995'),
    new phone_number('Germany', '+49'),
    new phone_number('Ghana', '+233'),
    new phone_number('Gibraltar', '+350'),
    new phone_number('Greece', '+30'),
    new phone_number('Greenland', '+299'),
    new phone_number('Grenada', '+1473'),
    new phone_number('Guadeloupe', '+590'),
    new phone_number('Guam', '+1671'),
    new phone_number('Guatemala', '+502'),
    new phone_number('Guinea', '+224'),
    new phone_number('Guinea-Bissau', '+245'),
    new phone_number('Guyana', '+592'),
    new phone_number('Haiti', '+509'),
    new phone_number('Honduras', '+504'),
    new phone_number('Hong Kong', '+852'),
    new phone_number('Hungary', '+36'),
    new phone_number('Iceland', '+354'),
    new phone_number('India', '+91'),
    new phone_number('Indonesia', '+62'),
    new phone_number('Iran', '+98'),
    new phone_number('Iraq', '+964'),
    new phone_number('Ireland', '+353'),
    new phone_number('Israel', '+972'),
    new phone_number('Italy', '+39'),
    new phone_number('Côte d’Ivoire', '+225'),
    new phone_number('Jamaica', '+1876'),
    new phone_number('Japan', '+81'),
    new phone_number('Jordan', '+962'),
    new phone_number('Kazakhstan', '+7'),
    new phone_number('Kenya', '+254'),
    new phone_number('Kiribati', '+686'),
    new phone_number('Kuwait', '+965'),
    new phone_number('Kyrgyzstan', '+996'),
    new phone_number('Laos', '+856'),
    new phone_number('Latvia', '+371'),
    new phone_number('Lebanon', '+961'),
    new phone_number('Lesotho', '+266'),
    new phone_number('Liberia', '+231'),
    new phone_number('Libya', '+218'),
    new phone_number('Liechtenstein', '+423'),
    new phone_number('Lithuania', '+370'),
    new phone_number('Luxembourg', '+352'),
    new phone_number('Macao', '+853'),
    new phone_number('North Macedonia', '+389'),
    new phone_number('Madagascar', '+261'),
    new phone_number('Malawi', '+265'),
    new phone_number('Malaysia', '+60'),
    new phone_number('Maldives', '+960'),
    new phone_number('Mali', '+223'),
    new phone_number('Malta', '+356'),
    new phone_number('Marshall Islands', '+692'),
    new phone_number('Martinique', '+596'),
    new phone_number('Mauritania', '+222'),
    new phone_number('Mauritius', '+230'),
    new phone_number('Mayotte', '+262'),
    new phone_number('Mexico', '+52'),
    new phone_number('Moldova', '+373'),
    new phone_number('Monaco', '+377'),
    new phone_number('Mongolia', '+976'),
    new phone_number('Montenegro', '+382'),
    new phone_number('Montserrat', '+1664'),
    new phone_number('Morocco', '+212'),
    new phone_number('Mozambique', '+258'),
    new phone_number('Namibia', '+264'),
    new phone_number('Nauru', '+674'),
    new phone_number('Nepal', '+977'),
    new phone_number('Netherlands', '+31'),
    new phone_number('Curaçao', '+599'),
    new phone_number('New Caledonia', '+687'),
    new phone_number('New Zealand', '+64'),
    new phone_number('Nicaragua', '+505'),
    new phone_number('Niger', '+227'),
    new phone_number('Nigeria', '+234'),
    new phone_number('Niue', '+683'),
    new phone_number('Norfolk Island', '+672'),
    new phone_number('Northern Mariana Islands', '+1670'),
    new phone_number('North Korea', '+850'),
    new phone_number('Norway', '+47'),
    new phone_number('Oman', '+968'),
    new phone_number('Pakistan', '+92'),
    new phone_number('Palau', '+680'),
    new phone_number('Palestine', '+970'),
    new phone_number('Panama', '+507'),
    new phone_number('Papua New Guinea', '+675'),
    new phone_number('Paraguay', '+595'),
    new phone_number('Peru', '+51'),
    new phone_number('Philippines', '+63'),
    new phone_number('Pitcairn Islands', '+870'),
    new phone_number('Poland', '+48'),
    new phone_number('Portugal', '+351'),
    new phone_number('Puerto Rico', '+1787'),
    new phone_number('Qatar', '+974'),
    new phone_number('Réunion', '+262'),
    new phone_number('Romania', '+40'),
    new phone_number('Russia', '+7'),
    new phone_number('Rwanda', '+250'),
    new phone_number('St. Helena', '+290'),
    new phone_number('St. Kitts & Nevis', '+1869'),
    new phone_number('St. Lucia', '+1758'),
    new phone_number('St. Martin', '+1599'),
    new phone_number('St. Pierre & Miquelon', '+508'),
    new phone_number('St. Vincent & Grenadines', '+1784'),
    new phone_number('Samoa', '+685'),
    new phone_number('San Marino', '+378'),
    new phone_number('São Tomé & Príncipe', '+239'),
    new phone_number('Saudi Arabia', '+966'),
    new phone_number('Senegal', '+221'),
    new phone_number('Serbia', '+381'),
    new phone_number('Seychelles', '+248'),
    new phone_number('Sierra Leone', '+232'),
    new phone_number('Singapore', '+65'),
    new phone_number('Slovakia', '+421'),
    new phone_number('Slovenia', '+386'),
    new phone_number('Solomon Islands', '+677'),
    new phone_number('Somalia', '+252'),
    new phone_number('South Africa', '+27'),
    new phone_number('South Korea', '+82'),
    new phone_number('South Sudan', '+211'),
    new phone_number('Spain', '+34'),
    new phone_number('Sri Lanka', '+94'),
    new phone_number('Sudan', '+249'),
    new phone_number('Suriname', '+597'),
    new phone_number('Eswatini', '+268'),
    new phone_number('Sweden', '+46'),
    new phone_number('Switzerland', '+41'),
    new phone_number('Syria', '+963'),
    new phone_number('Taiwan', '+886'),
    new phone_number('Tajikistan', '+992'),
    new phone_number('Tanzania', '+255'),
    new phone_number('Thailand', '+66'),
    new phone_number('Togo', '+228'),
    new phone_number('Tokelau', '+690'),
    new phone_number('Tonga', '+676'),
    new phone_number('Trinidad & Tobago', '+1868'),
    new phone_number('Tunisia', '+216'),
    new phone_number('Turkey', '+90'),
    new phone_number('Turkmenistan', '+993'),
    new phone_number('Turks & Caicos Islands', '+1649'),
    new phone_number('Tuvalu', '+688'),
    new phone_number('Uganda', '+256'),
    new phone_number('Ukraine', '+380'),
    new phone_number('United Arab Emirates', '+971'),
    new phone_number('Uruguay', '+598'),
    new phone_number('United States', '+1'),
    new phone_number('Uzbekistan', '+998'),
    new phone_number('Vanuatu', '+678'),
    new phone_number('Venezuela', '+58'),
    new phone_number('Vietnam', '+84'),
    new phone_number('U.S. Virgin Islands', '+1340'),
    new phone_number('Wallis & Futuna', '+681'),
    new phone_number('Yemen', '+967'),
    new phone_number('Zambia', '+260'),
    new phone_number('Zimbabwe', '+263')
);


?>
